### ISSUE TITLE
Options for python_requires directive?

### ISSUE THREAD

**Issue by hglick** [aazuspan/eerepr#13]
First off, this is a much needed module that will keep many of us from jumping back and forth between Python and JS for the ease of object inspection. Thank you for your efforts. 

I am currently working out of a Jupyter Lab setup built off a modified Docker image. The base structure is complicated enough that I don't want to tinker with it much, but my issue is that the image has python 3.7.1. The eerepr setup.cfg file has a python_requires directive of >=3.8, which made pip installing impossible. I manually cloned the repo from github, modified the file to accept 3.7.1, and ran an install from within my computing environment. It seems to work fine under light casual testing. So my question: Is the >=3.8 directive in place because of known issues with earlier versions of python, or is it possible (though perhaps untested), that your module works fine with <3.8?

**Comment by aazuspan** [comment]
Hi @hglick, sorry for the hassle with the install, but I'm glad you're finding it useful. 

I'm following the Numpy [Python support schedule](https://numpy.org/neps/nep-0029-deprecation_policy.html) which dropped 3.7 support last year, but I doubt you'll run into any issues with 3.7. As you guessed, it's just untested with earlier Python versions. 

For future reference or if anyone else comes across this issue, running `pip install eerepr --ignore-requires-python` should allow you to install into a <3.8 environment.

**Comment by hglick** [comment]
Many thanks for the response, @aazuspan . Great to hear that you don't think 3.7 will be an issue. I wasn't aware of the --ignore-requires-python, which I suspect will resolve a number of my current workflow struggles, so I certainly appreciate the tip. I'll post again if I see any other hiccups.
